# Generated by Django 3.1.4 on 2020-12-31 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highscore',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
